# Generated by Django 6.0 on 2026-05-19 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_inicio', models.DateField()),
                ('periodo_fin', models.DateField()),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deducciones', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bonificaciones', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_pago', models.DateField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.empleado')),
            ],
        ),
    ]
