# Generated by Django 6.0 on 2026-05-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_empleado_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='departamento',
            new_name='apellidos',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='user',
        ),
        migrations.AddField(
            model_name='empleado',
            name='edad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
