# Generated by Django 6.0 on 2026-05-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_rename_departamento_empleado_apellidos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='salario',
            field=models.CharField(),
        ),
    ]
